version: '3.8'

services:
  auth_db:
    image: postgres:15-alpine
    container_name: chameleon_auth_db
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: auth
    ports:
      - "5433:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      microservices-net:
        aliases:
          - auth

  redis_cache:
    image: redis:7-alpine
    container_name: chameleon_auth_redis
    ports:
      - "6379:6379"
    networks:
      - microservices-net

volumes:
  auth_postgres_data:

networks:
  microservices-net:
    driver: bridge
